version: "3"
services:
   www:
      container_name: tutorhubApache
      image: php:7.0.27-apache
      ports:
         - "8000:80"
      volumes:
         - ..:/var/www/html
      links:
         - db

   db:
      container_name: tutorhubDb
      image: mysql
      ports:
         - "3306"
      environment:
         MYSQL_DATABASE: csci311c
         MYSQL_USER: csci311c
         MYSQL_PASSWORD: semisecret
         MYSQL_ROOT_PASSWORD: supersecret
      volumes:
         - ./dump:/docker-entrypoint-initdb.d
         - persistent:/var/lib/mysql
volumes:
   persistent:
